# Fixed, locally maintained projection for the build exporter. No runtime GitHub fetch.
query Poe2UgNormalDocumentByIdQuery($input: Poe2UserGeneratedDocumentInputById!) {
 game: poe2 { documents { userGeneratedDocumentById(input: $input) { error data {
 ... on Poe2UserGeneratedDocument {
 id status updatedAt author { name creator { profileName } }
 data { name ... on Poe2UserGeneratedDocumentData {
 pobCode lootFilter buildVariants { values { id equipment { amulet { commonItem { slug isUnique isImported iconURL name itemClassSlug modifiers explicitDescriptions { description modifiers mustHave } implicitDescriptions { description modifiers mustHave } prefixes { mustHave slug } suffixes { modifiers mustHave slug } requirements { name value } stats { name value } poe2TradeRequest { query currentLeague } } anointment { slug } }
belt { commonItem { slug isUnique isImported iconURL name itemClassSlug modifiers explicitDescriptions { description modifiers mustHave } implicitDescriptions { description modifiers mustHave } prefixes { mustHave slug } suffixes { modifiers mustHave slug } requirements { name value } stats { name value } poe2TradeRequest { query currentLeague } } }
body { commonItem { slug isUnique isImported iconURL name itemClassSlug modifiers explicitDescriptions { description modifiers mustHave } implicitDescriptions { description modifiers mustHave } prefixes { mustHave slug } suffixes { modifiers mustHave slug } requirements { name value } stats { name value } poe2TradeRequest { query currentLeague } } runes { slug iconUrl } }
boots { commonItem { slug isUnique isImported iconURL name itemClassSlug modifiers explicitDescriptions { description modifiers mustHave } implicitDescriptions { description modifiers mustHave } prefixes { mustHave slug } suffixes { modifiers mustHave slug } requirements { name value } stats { name value } poe2TradeRequest { query currentLeague } } runes { slug iconUrl } }
flask1 { commonItem { slug isUnique isImported iconURL name itemClassSlug modifiers explicitDescriptions { description modifiers mustHave } implicitDescriptions { description modifiers mustHave } prefixes { mustHave slug } suffixes { modifiers mustHave slug } requirements { name value } stats { name value } poe2TradeRequest { query currentLeague } } }
flask2 { commonItem { slug isUnique isImported iconURL name itemClassSlug modifiers explicitDescriptions { description modifiers mustHave } implicitDescriptions { description modifiers mustHave } prefixes { mustHave slug } suffixes { modifiers mustHave slug } requirements { name value } stats { name value } poe2TradeRequest { query currentLeague } } }
charm1 { commonItem { slug isUnique isImported iconURL name itemClassSlug modifiers explicitDescriptions { description modifiers mustHave } implicitDescriptions { description modifiers mustHave } prefixes { mustHave slug } suffixes { modifiers mustHave slug } requirements { name value } stats { name value } poe2TradeRequest { query currentLeague } } }
charm2 { commonItem { slug isUnique isImported iconURL name itemClassSlug modifiers explicitDescriptions { description modifiers mustHave } implicitDescriptions { description modifiers mustHave } prefixes { mustHave slug } suffixes { modifiers mustHave slug } requirements { name value } stats { name value } poe2TradeRequest { query currentLeague } } }
charm3 { commonItem { slug isUnique isImported iconURL name itemClassSlug modifiers explicitDescriptions { description modifiers mustHave } implicitDescriptions { description modifiers mustHave } prefixes { mustHave slug } suffixes { modifiers mustHave slug } requirements { name value } stats { name value } poe2TradeRequest { query currentLeague } } }
gloves { commonItem { slug isUnique isImported iconURL name itemClassSlug modifiers explicitDescriptions { description modifiers mustHave } implicitDescriptions { description modifiers mustHave } prefixes { mustHave slug } suffixes { modifiers mustHave slug } requirements { name value } stats { name value } poe2TradeRequest { query currentLeague } } runes { slug iconUrl } }
helmet { commonItem { slug isUnique isImported iconURL name itemClassSlug modifiers explicitDescriptions { description modifiers mustHave } implicitDescriptions { description modifiers mustHave } prefixes { mustHave slug } suffixes { modifiers mustHave slug } requirements { name value } stats { name value } poe2TradeRequest { query currentLeague } } runes { slug iconUrl } }
leftRing { commonItem { slug isUnique isImported iconURL name itemClassSlug modifiers explicitDescriptions { description modifiers mustHave } implicitDescriptions { description modifiers mustHave } prefixes { mustHave slug } suffixes { modifiers mustHave slug } requirements { name value } stats { name value } poe2TradeRequest { query currentLeague } } }
extraRing { commonItem { slug isUnique isImported iconURL name itemClassSlug modifiers explicitDescriptions { description modifiers mustHave } implicitDescriptions { description modifiers mustHave } prefixes { mustHave slug } suffixes { modifiers mustHave slug } requirements { name value } stats { name value } poe2TradeRequest { query currentLeague } } }
rightRing { commonItem { slug isUnique isImported iconURL name itemClassSlug modifiers explicitDescriptions { description modifiers mustHave } implicitDescriptions { description modifiers mustHave } prefixes { mustHave slug } suffixes { modifiers mustHave slug } requirements { name value } stats { name value } poe2TradeRequest { query currentLeague } } }
mainHand { set1 { commonItem { slug isUnique isImported iconURL name itemClassSlug modifiers explicitDescriptions { description modifiers mustHave } implicitDescriptions { description modifiers mustHave } prefixes { mustHave slug } suffixes { modifiers mustHave slug } requirements { name value } stats { name value } poe2TradeRequest { query currentLeague } } providedSkill { gemSlug name iconURL gemIconURL } runes { slug iconUrl } } set2 { commonItem { slug isUnique isImported iconURL name itemClassSlug modifiers explicitDescriptions { description modifiers mustHave } implicitDescriptions { description modifiers mustHave } prefixes { mustHave slug } suffixes { modifiers mustHave slug } requirements { name value } stats { name value } poe2TradeRequest { query currentLeague } } providedSkill { gemSlug name iconURL gemIconURL } runes { slug iconUrl } } }
offHand { set1 { commonItem { slug isUnique isImported iconURL name itemClassSlug modifiers explicitDescriptions { description modifiers mustHave } implicitDescriptions { description modifiers mustHave } prefixes { mustHave slug } suffixes { modifiers mustHave slug } requirements { name value } stats { name value } poe2TradeRequest { query currentLeague } } providedSkill { gemSlug name iconURL gemIconURL } runes { slug iconUrl } } set2 { commonItem { slug isUnique isImported iconURL name itemClassSlug modifiers explicitDescriptions { description modifiers mustHave } implicitDescriptions { description modifiers mustHave } prefixes { mustHave slug } suffixes { modifiers mustHave slug } requirements { name value } stats { name value } poe2TradeRequest { query currentLeague } } providedSkill { gemSlug name iconURL gemIconURL } runes { slug iconUrl } } } }
 skillGems { gemRequirements { dex str int } gems { activeSkill { gemIconURL gemSlug iconURL name level } grantedByWeaponSet weaponSet subSkills { gemSlug iconURL gemType parentActiveSkillGemSlug } } priorityGems { gemSlug iconURL gemType description name parentActiveSkillGemSlug } }
 passiveTree { mainTree { selectedSlugs priorityList { slug name type iconURL description } } set1Tree { selectedSlugs } set2Tree { selectedSlugs } ascendancyTree { selectedSlugs priorityList { slug name type iconURL description } } attributeNodes { attribute nodeSlug } jewels { iconURL isUnique jewelSlug nodeSlug prefixSlugs suffixSlugs } }
 atlasTree { mainTree { selectedSlugs } breachTree { selectedSlugs } expeditionTree { selectedSlugs } deliriumTree { selectedSlugs } ritualTree { selectedSlugs } bossTree { selectedSlugs } pinnacleBossTree { selectedSlugs } abyssalTree { selectedSlugs } }
 } } } }
 content { __typename ... on NgfDocumentCmWidgetContentVariantsV1 { data { title childrenVariants { id title description { value } } } } }
 } } } } }
}