import {useCallback,useEffect,useRef,useState} from 'react'
import {X} from 'lucide-react'
import {UiButton} from './ui'
import {useMarketDialog} from './useMarketDialog'
import './RitualTracker.css'
import {costInDivine,type RitualCost} from './ritualCost'
type Item={id:string;name:string;category:string;price_divine:number;icon:string|null}
type Entry={key:string;name:string;quantity:number;status:'acquired'|'kept';price:number|null}
type Round={id:string;name:string;entries:Entry[];time:string;cost?:RitualCost}
const key='poe2-ritual-rounds-v1'
const empty=():Round=>({id:crypto.randomUUID(),name:'',entries:[],time:new Date().toISOString()})
function read(storageKey:string):Round[]{try{const value=JSON.parse(localStorage.getItem(storageKey)||'null');if(Array.isArray(value)&&value.length&&value.every(r=>typeof r.id==='string'&&Array.isArray(r.entries)&&r.entries.every((e:Entry)=>typeof e.name==='string'&&Number.isFinite(e.quantity)&&['seen','acquired','kept','deferred'].includes(e.status))))return value.map(r=>({...r,entries:r.entries.map((e:Omit<Entry,'status'> & {status:string})=>({...e,status:e.status==='deferred'?'kept':e.status==='seen'?'acquired':e.status}))}))}catch{}return [empty()]}
export function RitualTracker({onClose,markets,league}:{onClose:()=>void;markets:Item[];league:string}){
 const ref=useRef<HTMLElement>(null),[rounds,setRounds]=useState(()=>read(key+league)),[active,setActive]=useState(rounds[0].id),[query,setQuery]=useState(''),[all,setAll]=useState(false),[unit,setUnit]=useState<'divine'|'exalted'>('divine'),[expanded,setExpanded]=useState<string|null>(null),[error,setError]=useState(''),[sort,setSort]=useState('price'),[visible,setVisible]=useState(40),[notice,setNotice]=useState('')
 useMarketDialog(true,onClose,ref)
 useEffect(()=>{try{localStorage.setItem(key+league,JSON.stringify(rounds));setError('')}catch{setError('브라우저 저장에 실패했습니다. 기록을 다운로드해 주세요.')}},[rounds,league])
 const current=rounds.find(r=>r.id===active)||rounds[0]
 const update=useCallback((entries:Entry[])=>setRounds(rs=>rs.map(r=>r.id===current.id?{...r,entries}:r)),[current.id])
 const rate=markets.find(m=>m.id==='exchange:Currency:exalted')?.price_divine
 const vaalRate=markets.find(m=>m.id==='exchange:Currency:vaal')?.price_divine
 const editCost=(id:string,currency:'divine'|'exalted'|'vaal',value:number)=>{if(!Number.isFinite(value)||value<0||value>1e9)return;setRounds(rs=>rs.map(r=>{if(r.id!==id)return r;const previous=r.cost;return {...r,cost:{divine:0,exalted:0,vaal:0,...previous,[currency]:value,exaltedRate:previous?.exaltedRate??(rate&&rate>0?rate:null),vaalRate:previous?.vaalRate??(vaalRate&&vaalRate>0?vaalRate:null),at:previous?.at||new Date().toISOString()}}}))}
 const totalCost=rounds.map(r=>costInDivine(r.cost))
 const price=(n:number|null)=>n===null?'시세 없음':unit==='exalted'&&!(rate&&rate>0)?'환율 없음':`${(unit==='exalted'?n/rate!:n).toLocaleString('ko-KR',{maximumFractionDigits:3})} ${unit==='exalted'?'엑잘':'신성'}`
 const add=(item?:Item,status:Entry['status']='acquired')=>{const name=item?.name||query.trim();if(!name)return;update([...current.entries,{key:crypto.randomUUID(),name,quantity:1,status,price:item&&Number.isFinite(item.price_divine)?item.price_divine:null}]);setExpanded(current.id);setNotice(`${name} · ${status==='acquired'?'먹음':'킵'} 추가 완료`)}
 const choices=markets.filter(m=>(all||m.category==='Ritual')&&(!query.trim()||m.name.toLowerCase().includes(query.trim().toLowerCase()))).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'ko'):(b.price_divine??0)-(a.price_divine??0))
 const sum=(entries:Entry[])=>entries.reduce((n,e)=>n+(e.price??0)*e.quantity,0)
 const dip=(n:number|null)=>n===null?'환율 확인 필요':`${n.toLocaleString('ko-KR',{maximumFractionDigits:3})} 신성`
 const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({league,exportedAt:new Date().toISOString(),rounds},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='ritual-records.json';a.click();URL.revokeObjectURL(url)}
 return <section ref={ref} tabIndex={-1} className="ritual-tracker" role="dialog" aria-modal="true" aria-label="의식 보상 기록">
 <header><div><h2>의식 보상 기록</h2><p>판마다 먹음과 킵(공물 연기)을 나누고 보상 가치를 확인하세요.</p></div><UiButton aria-label="의식 기록 닫기" onClick={onClose}><X/></UiButton></header>
 <div className="ritual-layout"><aside><div className="ritual-target"><small>추가할 판</small><strong>{current.name||`${rounds.length-rounds.indexOf(current)}번째 판`}</strong></div><label>보상 이름 검색<div className="ritual-search-row"><input type="search" value={query} onChange={e=>{setQuery(e.target.value);setVisible(40)}} placeholder="예: 징조, 신성한 오브"/>{query&&<UiButton aria-label="검색어 지우기" onClick={()=>{setQuery('');setVisible(40)}}><X size={16}/></UiButton>}</div></label><div className="ritual-pick-filters"><UiButton aria-pressed={!all} onClick={()=>{setAll(false);setVisible(40)}}>의식 징조</UiButton><UiButton aria-pressed={all} onClick={()=>{setAll(true);setVisible(40)}}>전체 아이템</UiButton><select aria-label="아이템 정렬" value={sort} onChange={e=>setSort(e.target.value)}><option value="price">비싼 순</option><option value="name">ㄱㄴㄷ순</option></select></div><div className="ritual-pick-caption"><small>{choices.length.toLocaleString()}개 · 상태 버튼을 눌러 추가</small></div><p className="ritual-add-notice" role="status">{notice||'먹음은 획득, 킵은 공물 연기입니다.'}</p><div className="ritual-options">{choices.slice(0,visible).map(m=><div className="ritual-pick-item" key={m.id}>{m.icon&&<img src={m.icon} alt="" loading="lazy"/>}<div className="ritual-pick-name"><strong>{m.name}</strong><small>{price(m.price_divine)}</small></div><div className="ritual-pick-actions"><UiButton aria-label={`${m.name} 먹음 추가`} onClick={()=>add(m,'acquired')}>먹음</UiButton><UiButton aria-label={`${m.name} 킵 추가`} onClick={()=>add(m,'kept')}>킵</UiButton></div></div>)}</div>{choices.length>visible&&<UiButton className="ritual-more" onClick={()=>setVisible(n=>n+40)}>더 보기 · {visible}/{choices.length}</UiButton>}{!choices.length&&<p>검색 결과가 없습니다. 전체 아이템에서도 찾아보세요.</p>}{query.trim()&&!choices.some(m=>m.name===query.trim())&&<div className="ritual-custom"><small>“{query.trim()}” 직접 기록 · 시세 없음</small><UiButton onClick={()=>add(undefined,'acquired')}>먹음</UiButton><UiButton onClick={()=>add(undefined,'kept')}>킵</UiButton></div>}</aside>
 <main><div className="ritual-toolbar"><UiButton onClick={()=>{const r=empty();setRounds(rs=>[r,...rs]);setActive(r.id);setExpanded(r.id)}}>다음 판 시작</UiButton><UiButton onClick={download}>기록 다운로드</UiButton><UiButton aria-pressed={unit==='exalted'} onClick={()=>setUnit('exalted')}>엑잘</UiButton><UiButton aria-pressed={unit==='divine'} onClick={()=>setUnit('divine')}>신성</UiButton></div>
 <div className="ritual-session-summary"><div><small>전체 먹음</small><strong>{dip(sum(rounds.flatMap(r=>r.entries.filter(e=>e.status==='acquired'))))}</strong></div><div><small>전체 킵</small><strong>{dip(sum(rounds.flatMap(r=>r.entries.filter(e=>e.status==='kept'))))}</strong></div><div><small>전체 사용 금액</small><strong>{dip(totalCost.some(n=>n===null)?null:totalCost.reduce<number>((n,c)=>n+(c??0),0))}</strong></div><div><small>총합 · {rounds.length}판</small><strong>{dip(sum(rounds.flatMap(r=>r.entries)))}</strong></div></div><p className="ritual-list-hint">판을 눌러 상세 기록을 열 수 있습니다. 총합은 킵(공물 연기)을 포함한 가치입니다.</p>
 {error&&<p role="alert">{error}</p>}
 {[...rounds].reverse().map((round,index)=>{const acquired=round.entries.filter(e=>e.status==='acquired'),kept=round.entries.filter(e=>e.status==='kept');const open=expanded===round.id;return <section className="ritual-round" key={round.id}>
 <button className="ritual-round-summary" title={open?'상세 접기':'상세 보기'} aria-expanded={open} aria-controls={`ritual-round-${round.id}`} onClick={()=>{setActive(round.id);setExpanded(open?null:round.id)}}><div className="ritual-round-heading"><strong>{round.name||`${index+1}번째 판`}</strong>{round.id===active&&<span className="ritual-current">기록 중</span>}</div><div className="ritual-round-values"><div className="ritual-acquired"><small>먹음</small><strong>{dip(sum(acquired))}</strong></div><div><small>킵</small><strong>{dip(sum(kept))}</strong></div><div><small>사용 금액</small><strong>{dip(costInDivine(round.cost))}</strong></div><div><small>총합</small><strong>{dip(sum(round.entries))}</strong></div></div><span className="ritual-disclosure" aria-hidden="true">{open?'▲':'▼'}</span></button>
 {open&&<div id={`ritual-round-${round.id}`} className="ritual-round-detail"><div className="ritual-detail-meta"><span>{new Date(round.time).toLocaleString('ko-KR')}</span><span>먹음 {acquired.reduce((n,e)=>n+e.quantity,0)}개 · 킵 {kept.reduce((n,e)=>n+e.quantity,0)}개</span></div>{round.entries.some(e=>e.price===null)&&<p>시세 없는 보상 {round.entries.filter(e=>e.price===null).length}종은 합계에서 제외됩니다.</p>}<input aria-label="판 이름" placeholder="맵 이름·메모 입력" value={round.name} onChange={e=>setRounds(rs=>rs.map(r=>r.id===round.id?{...r,name:e.target.value}:r))}/>
 <div className="ritual-cost"><div className="ritual-cost-heading"><strong>사용 금액</strong><span>총 {dip(costInDivine(round.cost))}</span></div><div className="ritual-cost-inputs">{(['divine','exalted','vaal'] as const).map((currency,i)=><label key={currency}>{['신성','엑잘','바알'][i]}<input type="number" min="0" max="1000000000" step="any" inputMode="decimal" aria-label={`${index+1}번째 판 사용 ${['신성','엑잘','바알'][i]}`} value={round.cost?.[currency]??0} onChange={e=>editCost(round.id,currency,Number(e.target.value))}/></label>)}</div><small>신성 + 엑잘 × 엑잘 환율 + 바알 × 바알 환율. 환율은 입력 시 저장되며 보상 총합과 별도로 집계합니다.</small>{round.cost&&<small>저장 환율: 1 엑잘 = {round.cost.exaltedRate??'미확인'} 신성 · 1 바알 = {round.cost.vaalRate??'미확인'} 신성</small>}</div>
 {!round.entries.length?<div className="ritual-empty">왼쪽에서 보상을 추가하세요. 먹음으로 추가되며 킵으로 변경할 수 있습니다.</div>:round.entries.map(e=><article className="ritual-entry" key={e.key}><div><strong>{e.name}</strong><small>{price(e.price===null?null:e.price*e.quantity)} · 추가 당시 참고 시세</small></div><input type="number" min="1" max="999999" aria-label={`${e.name} 수량`} value={e.quantity} onChange={event=>{const quantity=Number(event.target.value);if(Number.isInteger(quantity)&&quantity>=1&&quantity<=999999)update(round.entries.map(x=>x.key===e.key?{...x,quantity}:x))}}/><div className="ritual-status">{(['acquired','kept'] as const).map((status,i)=><UiButton key={status} aria-pressed={e.status===status} onClick={()=>update(round.entries.map(x=>x.key===e.key?{...x,status}:x))}>{['먹음','킵'][i]}</UiButton>)}</div><UiButton aria-label={`${e.name} 기록 삭제`} onClick={()=>update(round.entries.filter(x=>x.key!==e.key))}><X size={16}/></UiButton></article>)}</div>}
 </section>})}
 <p className="ritual-note">먹음은 실제 획득, 킵은 공물 연기입니다. 총 가치는 먹음과 킵을 합한 참고 가치입니다. 기록은 이 기기 브라우저에 저장됩니다. 시세 없는 보상은 합계에서 제외하며 공물 비용·실제 판매 수익을 계산하지 않습니다.</p>
 </main></div></section>
}


