import {MarketIcon} from './MarketIcon'
import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react'
import {X} from 'lucide-react'
import {UiButton} from './ui'
import {useMarketDialog} from './useMarketDialog'
import './RitualTracker.css'
import {transferKept} from './ritualTransfer'
import {costInDivine,type RitualCost} from './ritualCost'
type Item={id:string;name:string;category:string;category_label?:string;price_divine:number;icon:string|null}
type Entry={key:string;name:string;quantity:number;status:'acquired'|'kept';price:number|null;originRoundId?:string;originEntryKey?:string;keptPrice?:number|null}
type Round={id:string;name:string;entries:Entry[];time:string;cost?:RitualCost}
const key='poe2-ritual-rounds-v1'
const empty=():Round=>({id:crypto.randomUUID(),name:'',entries:[],time:new Date().toISOString()})
function read(storageKey:string):Round[]{try{const value=JSON.parse(localStorage.getItem(storageKey)||'null');if(Array.isArray(value)&&value.length&&value.every(r=>typeof r.id==='string'&&Array.isArray(r.entries)&&r.entries.every((e:Entry)=>typeof e.name==='string'&&Number.isFinite(e.quantity)&&['seen','acquired','kept','deferred'].includes(e.status))))return value.map(r=>({...r,entries:r.entries.map((e:Omit<Entry,'status'> & {status:string})=>({...e,status:e.status==='deferred'?'kept':e.status==='seen'?'acquired':e.status}))}))}catch{}return [empty()]}
type Session={id:string;name:string;storageKey:string}
function readSessions(league:string):Session[]{let legacy=false;try{legacy=!!localStorage.getItem(key+league);const value=JSON.parse(localStorage.getItem('ritual-sessions-v1:'+league)||'null');if(Array.isArray(value)&&value.length&&value.every(s=>typeof s.id==='string'&&typeof s.name==='string'&&typeof s.storageKey==='string'))return value}catch{}return [{id:'legacy',name:legacy?'기존 기록':'세션 1',storageKey:key+league}]}
function SessionSummary({storageKey}:{storageKey:string}){let rounds:Round[]=[],cost:number|null=0;try{const raw=localStorage.getItem(storageKey);rounds=raw?read(storageKey):[];const saved=JSON.parse(localStorage.getItem(storageKey+':cost')||'null');const costs=saved?[costInDivine(saved)]:rounds.map(r=>costInDivine(r.cost));cost=costs.some(n=>n===null)?null:costs.reduce<number>((n,c)=>n+(c??0),0)}catch{}const entries=rounds.flatMap(r=>r.entries);const sum=(status?:Entry['status'])=>entries.filter(e=>!status||e.status===status).reduce((n,e)=>n+(e.price??0)*e.quantity,0);const format=(value:number|null)=>value===null?'환율 필요':`${value.toLocaleString('ko-KR',{maximumFractionDigits:3})} 신성`;return <span className="ritual-tab-summary"><span className="ritual-tab-count">{rounds.length}판</span><span><small>먹음</small><b>{format(sum('acquired'))}</b></span><span><small>킵</small><b>{format(sum('kept'))}</b></span><span><small>비용</small><b>{format(cost)}</b></span><span><small>총합</small><b>{format(sum())}</b></span></span>}
export function RitualTracker({onClose,markets,league}:{onClose:()=>void;markets:Item[];league:string}){
 const [sessions,setSessions]=useState(()=>readSessions(league)),[selected,setSelected]=useState(sessions[0].id),[sessionError,setSessionError]=useState('')
 const [,setRevision]=useState(0)
 const onSaved=useCallback(()=>setRevision(n=>n+1),[])
 const session=sessions.find(s=>s.id===selected)||sessions[0]
 useEffect(()=>{try{localStorage.setItem('ritual-sessions-v1:'+league,JSON.stringify(sessions));setSessionError('')}catch{setSessionError('세션 저장에 실패했습니다. 기록을 다운로드해 주세요.')}},[sessions,league])
 const selectSession=(id:string)=>setSelected(id)
 const nav=<div className="ritual-sessions"><div className="ritual-session-tabs" role="tablist" aria-label="의식 기록 세션">{sessions.map((s,i)=><button key={s.id} type="button" role="tab" id={`ritual-session-tab-${s.id}`} aria-selected={session.id===s.id} aria-controls="ritual-session-panel" tabIndex={session.id===s.id?0:-1} onClick={()=>selectSession(s.id)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?sessions.length-1:(i+(e.key==='ArrowRight'?1:-1)+sessions.length)%sessions.length;selectSession(sessions[next].id);document.getElementById(`ritual-session-tab-${sessions[next].id}`)?.focus()}}}><span className="ritual-tab-title">{s.name||'이름 없는 세션'}</span><SessionSummary storageKey={s.storageKey}/></button>)}</div><UiButton onClick={()=>{const id=crypto.randomUUID();setSessions(ss=>[...ss,{id,name:`세션 ${ss.length+1}`,storageKey:key+league+':'+id}]);setSelected(id)}}>＋ 새 세션</UiButton><label>세션 이름<input value={session.name} maxLength={60} onChange={e=>setSessions(ss=>ss.map(s=>s.id===session.id?{...s,name:e.target.value}:s))}/></label>{sessionError&&<p role="alert">{sessionError}</p>}</div>
 return <RitualSession key={session.id} onClose={onClose} markets={markets} league={league} storageKey={session.storageKey} sessionName={session.name} sessionId={session.id} nav={nav} onSaved={onSaved}/>
}
function RitualSession({onClose,markets,league,storageKey,sessionName,sessionId,nav,onSaved}:{onClose:()=>void;markets:Item[];league:string;storageKey:string;sessionName:string;sessionId:string;nav:ReactNode;onSaved:()=>void}){
 const ref=useRef<HTMLElement>(null),[rounds,setRounds]=useState(()=>read(storageKey)),[active,setActive]=useState(rounds[0].id),[query,setQuery]=useState(''),[all,setAll]=useState(false),[unit,setUnit]=useState<'divine'|'exalted'>('divine'),[expanded,setExpanded]=useState<string|null>(null),[error,setError]=useState(''),[view,setView]=useState<'list'|'cards'>('list'),[sort,setSort]=useState('price'),[visible,setVisible]=useState(40),[notice,setNotice]=useState(''),[transferAmounts,setTransferAmounts]=useState<Record<string,number>>({})
 useMarketDialog(true,onClose,ref)
 useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify(rounds));onSaved();setError('')}catch{setError('브라우저 저장에 실패했습니다. 기록을 다운로드해 주세요.')}},[rounds,storageKey,onSaved])
 const startNextRound=()=>{const r=empty();setRounds(rs=>[r,...rs]);setActive(r.id);setExpanded(r.id);requestAnimationFrame(()=>requestAnimationFrame(()=>document.getElementById(`ritual-round-${r.id}`)?.scrollIntoView({block:'nearest',behavior:'smooth'})))}
 const current=rounds.find(r=>r.id===active)||rounds[0]
 const previousKeeps=rounds.slice(rounds.indexOf(current)+1).flatMap(r=>r.entries.filter(e=>e.status==='kept').map(e=>({round:r,entry:e})))
 const moveKeep=(source:Round,entry:Entry)=>{const quantity=transferAmounts[entry.key]??1;const matches=markets.filter(m=>m.name===entry.name);const quote=matches.length===1&&Number.isFinite(matches[0].price_divine)?matches[0].price_divine:null;const newKey=crypto.randomUUID();setRounds(rs=>transferKept(rs,source.id,current.id,entry.key,quantity,newKey,quote));setExpanded(current.id);setNotice(`${entry.name} ${quantity}개 · 이전 킵에서 먹음으로 이동`)}
 const update=useCallback((entries:Entry[])=>setRounds(rs=>rs.map(r=>r.id===current.id?{...r,entries}:r)),[current.id])
 const setQuantity=(round:Round,name:string,status:Entry['status'],quantity:number)=>{
  if(!Number.isInteger(quantity)||quantity<0||quantity>999999)return
  const matches=round.entries.filter(e=>e.name===name&&e.status===status)
  let remaining=quantity
  const entries=round.entries.flatMap(e=>{if(e.name!==name||e.status!==status)return [e];const count=Math.min(remaining,e.quantity);remaining-=count;return count?[{...e,quantity:count}]:[]})
  if(remaining){const source=matches.at(-1)||round.entries.find(e=>e.name===name);entries.push({key:crypto.randomUUID(),name,status,quantity:remaining,price:source?.price??null})}
  setRounds(rs=>rs.map(r=>r.id===round.id?{...r,entries}:r))
 }
 const rate=markets.find(m=>m.id==='exchange:Currency:exalted')?.price_divine
 const vaalRate=markets.find(m=>m.id==='exchange:Currency:vaal')?.price_divine
 const [sessionCost,setSessionCost]=useState<RitualCost>(()=>{try{const stored=JSON.parse(localStorage.getItem(storageKey+':cost')||'null');if(stored&&['divine','exalted','vaal'].every(k=>typeof stored[k]==='number'&&Number.isFinite(stored[k])&&stored[k]>=0))return stored}catch{}const costs=rounds.flatMap(r=>r.cost?[r.cost]:[]);const total=(k:'divine'|'exalted'|'vaal')=>costs.reduce((n,c)=>n+c[k],0);const mergedRate=(currency:'exalted'|'vaal',field:'exaltedRate'|'vaalRate')=>{const used=costs.filter(c=>c[currency]>0);return used.some(c=>!(c[field]!==null&&Number.isFinite(c[field])&&c[field]!>0))?null:total(currency)>0?used.reduce((n,c)=>n+c[currency]*c[field]!,0)/total(currency):null};return {divine:total('divine'),exalted:total('exalted'),vaal:total('vaal'),exaltedRate:mergedRate('exalted','exaltedRate'),vaalRate:mergedRate('vaal','vaalRate'),at:new Date().toISOString()}})
 useEffect(()=>{try{localStorage.setItem(storageKey+':cost',JSON.stringify(sessionCost));onSaved()}catch{setError('세션 비용 저장에 실패했습니다. 기록을 다운로드해 주세요.')}},[sessionCost,storageKey,onSaved])
 const editCost=(currency:'divine'|'exalted'|'vaal',value:number)=>{if(!Number.isFinite(value)||value<0||value>1e9)return;setSessionCost(previous=>({...previous,[currency]:value,exaltedRate:previous.exaltedRate??(rate&&rate>0?rate:null),vaalRate:previous.vaalRate??(vaalRate&&vaalRate>0?vaalRate:null)}))}
 const price=(n:number|null)=>n===null?'시세 없음':unit==='exalted'&&!(rate&&rate>0)?'환율 없음':`${(unit==='exalted'?n/rate!:n).toLocaleString('ko-KR',{maximumFractionDigits:3})} ${unit==='exalted'?'엑잘':'신성'}`
 const add=(item?:Item,status:Entry['status']='acquired')=>{const name=item?.name||query.trim();if(!name)return;update([...current.entries,{key:crypto.randomUUID(),name,quantity:1,status,price:item&&Number.isFinite(item.price_divine)?item.price_divine:null}]);setExpanded(current.id);setNotice(`${name} · ${status==='acquired'?'먹음':'킵'} 추가 완료`)}
 const choices=markets.filter(m=>(all||m.category==='Ritual')&&(!query.trim()||m.name.toLowerCase().includes(query.trim().toLowerCase()))).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'ko'):(b.price_divine??0)-(a.price_divine??0))
 const shortName=(name:string)=>name.replace(/의 징조$/, '').replace(/ 징조$/, '')
 const groupName=(item:Item)=>item.category==='Ritual'?(item.name.startsWith('좌측')?'좌측 징조':item.name.startsWith('우측')?'우측 징조':'기타 징조'):(item.category_label||item.category)
 const groups=[...new Set(choices.slice(0,visible).map(groupName))]
 const sum=(entries:Entry[])=>entries.reduce((n,e)=>n+(e.price??0)*e.quantity,0)
 const dip=(n:number|null)=>n===null?'환율 확인 필요':`${n.toLocaleString('ko-KR',{maximumFractionDigits:3})} 신성`
 const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({league,sessionName,sessionCost,exportedAt:new Date().toISOString(),rounds},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='ritual-records.json';a.click();URL.revokeObjectURL(url)}
 return <section ref={ref} tabIndex={-1} className="ritual-tracker" role="dialog" aria-modal="true" aria-label="의식 보상 기록">
 <header><div><h2>의식 보상 기록</h2><p>판마다 먹음과 킵(공물 연기)을 나누고 보상 가치를 확인하세요.</p></div><UiButton aria-label="의식 기록 닫기" onClick={onClose}><X/></UiButton></header>{nav}
 <div className="ritual-layout"><aside><div className="ritual-target"><small>추가할 판</small><strong>{current.name||`${rounds.length-rounds.indexOf(current)}번째 판`}</strong></div><label>보상 이름 검색<div className="ritual-search-row"><input type="search" value={query} onChange={e=>{setQuery(e.target.value);setVisible(40)}} placeholder="예: 징조, 신성한 오브"/>{query&&<UiButton aria-label="검색어 지우기" onClick={()=>{setQuery('');setVisible(40)}}><X size={16}/></UiButton>}</div></label><div className="ritual-pick-filters"><UiButton aria-pressed={!all} onClick={()=>{setAll(false);setVisible(40)}}>의식 징조</UiButton><UiButton aria-pressed={all} onClick={()=>{setAll(true);setVisible(40)}}>전체 아이템</UiButton><select aria-label="아이템 정렬" value={sort} onChange={e=>setSort(e.target.value)}><option value="price">비싼 순</option><option value="name">ㄱㄴㄷ순</option></select></div><div className="ritual-view-switch" role="group" aria-label="아이템 선택 보기"><UiButton aria-pressed={view==='list'} onClick={()=>setView('list')}>목록</UiButton><UiButton aria-pressed={view==='cards'} onClick={()=>setView('cards')}>아이콘 · 분류별</UiButton></div><div className="ritual-pick-caption"><small>{choices.length.toLocaleString()}개 · 상태 버튼을 눌러 추가</small></div><p className="ritual-add-notice" role="status">{notice||'먹음은 획득, 킵은 공물 연기입니다.'}</p><div className="ritual-options">{view==='cards'?groups.map(group=><section className="ritual-card-group" key={group}><h3>{group}</h3><div className="ritual-card-grid">{choices.slice(0,visible).filter(item=>groupName(item)===group).map(item=><article className="ritual-icon-card" key={item.id} title={item.name}><MarketIcon market={{id:item.id,league}}/><strong>{shortName(item.name)}</strong><small>{price(item.price_divine)}</small><div><UiButton aria-label={`${item.name} 먹음 추가`} onClick={()=>add(item,'acquired')}>먹음</UiButton><UiButton aria-label={`${item.name} 킵 추가`} onClick={()=>add(item,'kept')}>킵</UiButton></div></article>)}</div></section>):choices.slice(0,visible).map(m=><div className="ritual-pick-item" key={m.id}><MarketIcon market={{id:m.id,league}}/><div className="ritual-pick-name"><strong>{m.name}</strong><small>{price(m.price_divine)}</small></div><div className="ritual-pick-actions"><UiButton aria-label={`${m.name} 먹음 추가`} onClick={()=>add(m,'acquired')}>먹음</UiButton><UiButton aria-label={`${m.name} 킵 추가`} onClick={()=>add(m,'kept')}>킵</UiButton></div></div>)}</div>{choices.length>visible&&<UiButton className="ritual-more" onClick={()=>setVisible(n=>n+40)}>더 보기 · {visible}/{choices.length}</UiButton>}{!choices.length&&<p>검색 결과가 없습니다. 전체 아이템에서도 찾아보세요.</p>}{query.trim()&&!choices.some(m=>m.name===query.trim())&&<div className="ritual-custom"><small>“{query.trim()}” 직접 기록 · 시세 없음</small><UiButton onClick={()=>add(undefined,'acquired')}>먹음</UiButton><UiButton onClick={()=>add(undefined,'kept')}>킵</UiButton></div>}</aside>
 <main role="tabpanel" id="ritual-session-panel" aria-labelledby={`ritual-session-tab-${sessionId}`}><div className="ritual-toolbar"><UiButton onClick={startNextRound}>다음 판 시작</UiButton><UiButton onClick={download}>기록 다운로드</UiButton><UiButton aria-pressed={unit==='exalted'} onClick={()=>setUnit('exalted')}>엑잘</UiButton><UiButton aria-pressed={unit==='divine'} onClick={()=>setUnit('divine')}>신성</UiButton></div>
 <div className="ritual-cost"><div className="ritual-cost-heading"><strong>세션 사용 금액</strong><span>총 {dip(costInDivine(sessionCost))}</span></div><div className="ritual-cost-inputs">{(['divine','exalted','vaal'] as const).map((currency,i)=><label key={currency}>{['신성','엑잘','바알'][i]}<input type="number" min="0" max="1000000000" step="any" inputMode="decimal" aria-label={`세션 사용 ${['신성','엑잘','바알'][i]}`} value={sessionCost?.[currency]??0} onChange={e=>editCost(currency,Number(e.target.value))}/></label>)}</div><small>신성 + 엑잘 × 엑잘 환율 + 바알 × 바알 환율. 환율은 입력 시 저장되며 보상 총합과 별도로 집계합니다.</small>{sessionCost&&<small>저장 환율: 1 엑잘 = {sessionCost.exaltedRate??'미확인'} 신성 · 1 바알 = {sessionCost.vaalRate??'미확인'} 신성</small>}</div>
 <details className="ritual-previous-keeps"><summary>이전 킵 → 먹음으로 이동 <strong>{previousKeeps.reduce((n,k)=>n+k.entry.quantity,0)}개</strong></summary><p>현재 기록할 판: {current.name||`${rounds.length-rounds.indexOf(current)}번째 판`}. 이동한 수량은 이전 킵에서 빠집니다.</p>{!previousKeeps.length?<p>이전 판에 남아 있는 킵이 없습니다.</p>:previousKeeps.map(({round,entry})=><div className="ritual-keep-transfer" key={entry.key}><div><strong>{entry.name}</strong><small>{round.name||`${rounds.length-rounds.indexOf(round)}번째 판`} · 킵 {entry.quantity}개</small></div><input aria-label={`${entry.name} 이전 킵 이동 수량`} type="number" min="1" max={entry.quantity} value={transferAmounts[entry.key]??1} onChange={e=>{const quantity=Number(e.target.value);if(Number.isInteger(quantity)&&quantity>=1&&quantity<=entry.quantity)setTransferAmounts(values=>({...values,[entry.key]:quantity}))}}/><UiButton disabled={(transferAmounts[entry.key]??1)>entry.quantity} onClick={()=>moveKeep(round,entry)}>먹음으로 이동</UiButton></div>)}</details>
 <div className="ritual-session-summary"><div><small>세션 먹음</small><strong>{dip(sum(rounds.flatMap(r=>r.entries.filter(e=>e.status==='acquired'))))}</strong></div><div><small>세션 킵</small><strong>{dip(sum(rounds.flatMap(r=>r.entries.filter(e=>e.status==='kept'))))}</strong></div><div><small>세션 사용 금액</small><strong>{dip(costInDivine(sessionCost))}</strong></div><div><small>총합 · {rounds.length}판</small><strong>{dip(sum(rounds.flatMap(r=>r.entries)))}</strong></div></div><p className="ritual-list-hint">판을 눌러 상세 기록을 열 수 있습니다. 총합은 킵(공물 연기)을 포함한 가치입니다.</p>
 {error&&<p role="alert">{error}</p>}
 {[...rounds].reverse().map((round,index)=>{const acquired=round.entries.filter(e=>e.status==='acquired'),kept=round.entries.filter(e=>e.status==='kept');const open=expanded===round.id;return <section className="ritual-round" key={round.id}>
 <button className="ritual-round-summary" title={open?'상세 접기':'상세 보기'} aria-expanded={open} aria-controls={`ritual-round-${round.id}`} onClick={()=>{setActive(round.id);setExpanded(open?null:round.id)}}><div className="ritual-round-heading"><strong>{round.name||`${index+1}번째 판`}</strong>{round.id===active&&<span className="ritual-current">기록 중</span>}</div><div className="ritual-round-values"><div className="ritual-acquired"><small>먹음</small><strong>{dip(sum(acquired))}</strong></div><div><small>킵</small><strong>{dip(sum(kept))}</strong></div><div><small>총합</small><strong>{dip(sum(round.entries))}</strong></div></div><span className="ritual-disclosure" aria-hidden="true">{open?'▲':'▼'}</span></button>
 {open&&<div id={`ritual-round-${round.id}`} className="ritual-round-detail"><div className="ritual-detail-meta"><span>{new Date(round.time).toLocaleString('ko-KR')}</span><span>먹음 {acquired.reduce((n,e)=>n+e.quantity,0)}개 · 킵 {kept.reduce((n,e)=>n+e.quantity,0)}개</span></div>{round.entries.some(e=>e.price===null)&&<p>시세 없는 보상 {round.entries.filter(e=>e.price===null).length}종은 합계에서 제외됩니다.</p>}<input aria-label="판 이름" placeholder="맵 이름·메모 입력" value={round.name} onChange={e=>setRounds(rs=>rs.map(r=>r.id===round.id?{...r,name:e.target.value}:r))}/>

 {!round.entries.length?<div className="ritual-empty">왼쪽에서 보상을 추가하세요. 먹음으로 추가되며 킵으로 변경할 수 있습니다.</div>:[...new Set(round.entries.map(e=>e.name))].map(name=>{const entries=round.entries.filter(e=>e.name===name);return <article className="ritual-entry" key={name}><div><strong>{name}</strong>{entries.some(e=>e.originRoundId)&&<small>이전 킵에서 획득 · {entries.filter(e=>e.originRoundId).reduce((n,e)=>n+e.quantity,0)}개</small>}<small>{entries.some(e=>e.price===null)?'시세 없는 수량 포함 · ':''}{price(sum(entries))} · 합산 참고 가치</small></div><div className="ritual-quantities">{(['acquired','kept'] as const).map((status,i)=><label key={status}><span>{['먹음','킵'][i]}</span><input type="number" min="0" max="999999" inputMode="numeric" aria-label={`${name} ${['먹음','킵'][i]} 수량`} value={entries.filter(e=>e.status===status).reduce((n,e)=>n+e.quantity,0)} onChange={event=>setQuantity(round,name,status,Number(event.target.value))}/><small>개</small></label>)}</div><UiButton aria-label={`${name} 기록 삭제`} onClick={()=>update(round.entries.filter(e=>e.name!==name))}><X size={16}/></UiButton></article>})}</div>}
 <div className="ritual-round-footer"><UiButton onClick={startNextRound}>다음 판 시작 ＋</UiButton></div></section>})}
 <p className="ritual-note">먹음은 실제 획득, 킵은 공물 연기입니다. 총 가치는 먹음과 킵을 합한 참고 가치입니다. 기록은 이 기기 브라우저에 저장됩니다. 시세 없는 보상은 합계에서 제외하며 공물 비용·실제 판매 수익을 계산하지 않습니다.</p>
 </main></div></section>
}



